export { default } from './src/core.js'
export { signal, effect, computed, batch } from './src/signal.js'

import './directive/if.js'
import './directive/each.js'
import './directive/ref.js'
import './directive/scope.js'
import './directive/html.js'
import './directive/text.js'
import './directive/class.js'
import './directive/style.js'
import './directive/value.js'
import './directive/default.js'
